name: Deploy sitemap to Pages

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '30 14 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version you want to use

      - name: Install dependencies
        run: |
          npm install fs jsdom

      - name: Generate sitemap
        run: |
          curl -o index.html https://nikita-kun.github.io
          node generateSitemap.js

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'deploy'  # Path to the directory containing sitemap.xml

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
